from __future__ import annotations

import argparse
import math
from pathlib import Path
from types import SimpleNamespace

import torch

from .reference import HyperConnection, LearnedRouter, sqrtsoftplus

SOURCE_COMMIT = "13952eff5dcf75ce75e692d5a03e714e47de2fd4"


def c_float(value: torch.Tensor | float) -> str:
    number = float(value)
    if math.isnan(number):
        return "NAN"
    if math.isinf(number):
        return "INFINITY" if number > 0 else "-INFINITY"
    return f"{number.hex()}f"


def emit_array(name: str, values: torch.Tensor, ctype: str = "float", per_line: int = 4) -> str:
    flat = values.detach().cpu().reshape(-1).tolist()
    lines = [f"static const {ctype} {name}[{len(flat)}] = {{"]
    for start in range(0, len(flat), per_line):
        chunk = flat[start : start + per_line]
        if ctype == "float":
            rendered = ", ".join(c_float(value) for value in chunk)
        else:
            rendered = ", ".join(f"{int(value)}u" for value in chunk)
        suffix = "," if start + per_line < len(flat) else ""
        lines.append(f"    {rendered}{suffix}")
    lines.append("};")
    return "\n".join(lines)


def build_header() -> str:
    sqrt_input = torch.tensor([-20.0, -3.0, -1.0, 0.0, 1.0, 3.0, 20.0], dtype=torch.float32)
    # Transcendental kernels can differ by one ULP across runner CPU capabilities.
    # Emit one reviewed FP32 contract and verify that the live PyTorch oracle remains
    # numerically equivalent instead of letting the vendored header depend on ISA/libm.
    sqrt_expected = torch.tensor(
        [
            float.fromhex("0x1.7cd79c0000000p-15"),
            float.fromhex("0x1.c36e640000000p-3"),
            float.fromhex("0x1.1e90b80000000p-1"),
            float.fromhex("0x1.aa44980000000p-1"),
            float.fromhex("0x1.255eb40000000p+0"),
            float.fromhex("0x1.befb320000000p+0"),
            float.fromhex("0x1.1e377a0000000p+2"),
        ],
        dtype=torch.float32,
    )
    torch.testing.assert_close(
        sqrtsoftplus(sqrt_input), sqrt_expected, rtol=0.0, atol=4.0e-8
    )

    route_cfg = SimpleNamespace(
        hidden_size=4,
        num_experts_per_token=6,
        num_routed_experts=8,
        routed_scaling_factor=1.5,
    )
    hidden = torch.tensor(
        [[1.0, -0.5, 0.25, 0.75], [-0.2, 0.4, 1.0, -0.6]], dtype=torch.float32
    )
    expert_weight = torch.tensor(
        [
            [0.10, -0.20, 0.05, 0.30],
            [-0.15, 0.25, 0.40, -0.10],
            [0.35, 0.05, -0.25, 0.20],
            [-0.40, 0.30, 0.15, 0.05],
            [0.22, -0.33, 0.18, -0.12],
            [-0.08, 0.12, -0.45, 0.38],
            [0.31, 0.27, 0.09, -0.29],
            [-0.26, -0.11, 0.37, 0.24],
        ],
        dtype=torch.float32,
    )
    correction_bias = torch.tensor(
        [0.40, -0.30, 0.20, -0.10, 0.10, -0.20, 0.30, -0.40], dtype=torch.float32
    )
    router = LearnedRouter(route_cfg)
    with torch.no_grad():
        router.weight.copy_(expert_weight)
        router.correction_bias.copy_(correction_bias)
    logits, _, unsorted_indices = router(hidden.view(1, 2, 4))
    scores = sqrtsoftplus(logits)
    corrected = scores + correction_bias
    sorted_indices = torch.topk(corrected, route_cfg.num_experts_per_token, dim=-1, sorted=True).indices
    assert torch.equal(
        torch.sort(unsorted_indices, dim=-1).values,
        torch.sort(sorted_indices, dim=-1).values,
    )
    sorted_corrected = torch.sort(corrected, dim=-1, descending=True).values
    assert torch.all(sorted_corrected[:, :-1] - sorted_corrected[:, 1:] > 1e-6)
    route_weights = scores.gather(1, sorted_indices)
    route_weights = route_weights / (route_weights.sum(dim=-1, keepdim=True) + 1e-20)
    route_weights = route_weights * route_cfg.routed_scaling_factor

    hc_cfg = SimpleNamespace(
        hidden_size=3,
        hc_mult=4,
        hc_sinkhorn_iters=20,
        hc_eps=1e-6,
        rms_norm_eps=1e-6,
    )
    streams = torch.tensor(
        [
            [0.25, -0.50, 0.75],
            [-0.10, 0.20, -0.30],
            [0.90, 0.40, -0.20],
            [-0.60, 0.80, 0.10],
        ],
        dtype=torch.float32,
    )
    hc = HyperConnection(hc_cfg)
    mix = (2 + hc_cfg.hc_mult) * hc_cfg.hc_mult
    fn = torch.empty(mix, hc_cfg.hc_mult * hc_cfg.hidden_size, dtype=torch.float32)
    for out in range(mix):
        for inner in range(hc_cfg.hc_mult * hc_cfg.hidden_size):
            fn[out, inner] = (((out * 13 + inner * 7) % 23) - 11) / 100.0
    base = torch.linspace(-0.1, 0.1, mix, dtype=torch.float32)
    scale = torch.tensor([0.9, 1.1, 0.8], dtype=torch.float32)
    with torch.no_grad():
        hc.fn.copy_(fn)
        hc.base.copy_(base)
        hc.scale.copy_(scale)
    post, comb, collapsed = hc(streams.view(1, 1, 4, 3))

    preamble = f"""/* Generated by tools/dsv4_mini/make_c_ops_fixture.py.
 * Canonical source: tools/dsv4_mini/reference.py
 * Source commit: {SOURCE_COMMIT}
 * Do not edit by hand.
 */
#ifndef DSV4_CPU_OPS_VECTORS_H
#define DSV4_CPU_OPS_VECTORS_H

#define DSV4_VEC_SQRT_COUNT 7u
#define DSV4_VEC_ROUTE_ROWS 2u
#define DSV4_VEC_ROUTE_HIDDEN 4u
#define DSV4_VEC_ROUTE_EXPERTS 8u
#define DSV4_VEC_ROUTE_TOPK 6u
#define DSV4_VEC_HC 4u
#define DSV4_VEC_HIDDEN 3u
#define DSV4_VEC_HC_MIX 24u
"""
    arrays = [
        emit_array("dsv4_vec_sqrt_input", sqrt_input),
        emit_array("dsv4_vec_sqrt_expected", sqrt_expected),
        emit_array("dsv4_vec_route_hidden", hidden),
        emit_array("dsv4_vec_route_weight", expert_weight),
        emit_array("dsv4_vec_route_bias", correction_bias),
        emit_array("dsv4_vec_route_logits", logits),
        emit_array("dsv4_vec_route_indices", sorted_indices, "unsigned", 6),
        emit_array("dsv4_vec_route_weights", route_weights),
        emit_array("dsv4_vec_hc_streams", streams),
        emit_array("dsv4_vec_hc_base", base),
        emit_array("dsv4_vec_hc_scale", scale, per_line=3),
        emit_array("dsv4_vec_hc_post", post),
        emit_array("dsv4_vec_hc_comb", comb),
        emit_array("dsv4_vec_hc_collapsed", collapsed, per_line=3),
    ]
    return preamble + "\n\n" + "\n\n".join(arrays) + "\n\n#endif\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(build_header(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
