from __future__ import annotations

import argparse
from pathlib import Path

import torch

from .make_decoder_layer_fixture import decoder_config
from .make_model_shell_fixture import emit_float_array, emit_uint_array, fill_base_model, token_for
from .make_mtp_fixture import fill_mtp
from .reference import MiniReferenceModel

SOURCE_COMMIT = "b4355d29a2e410ca4555ae8e129b3983f3f07d97"
STEPS = 20
PROMPT_LEN = 7
MAX_NEW = 5


def build_header() -> str:
    torch.set_num_threads(1)
    config = decoder_config()
    model = MiniReferenceModel(config).eval()
    fill_base_model(model)
    fill_mtp(model)

    state = model.new_state(batch_size=1, device="cpu", dtype=torch.float32)
    tokens: list[int] = []
    base_logits: list[float] = []
    mtp_logits: list[float] = []
    base_argmax: list[int] = []
    mtp_argmax: list[int] = []
    mtp_routes: list[int] = []
    mtp_route_weights: list[float] = []

    for position in range(STEPS):
        token = token_for(position, config.vocab_size)
        ids = torch.tensor([[token]], dtype=torch.long)
        output = model.step(ids, state)
        tokens.append(token)
        base_logits.extend(float(value) for value in output.logits.reshape(-1).tolist())
        mtp_logits.extend(float(value) for value in output.mtp_logits.reshape(-1).tolist())
        base_argmax.append(int(output.logits.argmax(dim=-1).item()))
        mtp_argmax.append(int(output.mtp_logits.argmax(dim=-1).item()))
        mtp_routes.extend(int(value) for value in output.trace.mtp.route_indices)
        mtp_route_weights.extend(float(value) for value in output.trace.mtp.route_weights)

    prompt_values = [token_for(position, config.vocab_size) for position in range(PROMPT_LEN)]
    prompt = torch.tensor([prompt_values], dtype=torch.long)
    generated = model.generate(prompt, max_new_tokens=MAX_NEW)[0].tolist()

    preamble = f"""/* Generated by tools/dsv4_mini/make_full_runtime_fixture.py.
 * Canonical source: MiniReferenceModel.step + MiniReferenceModel.generate.
 * Base source commit: {SOURCE_COMMIT}
 * Weight arrays are reused from the P1-I/P1-J canonical fixture headers.
 * Do not edit by hand.
 */
#ifndef DSV4_FULL_RUNTIME_VECTORS_H
#define DSV4_FULL_RUNTIME_VECTORS_H

#define DSV4_FULL_STEPS {STEPS}u
#define DSV4_FULL_VOCAB {config.vocab_size}u
#define DSV4_FULL_TOPK {config.num_experts_per_token}u
#define DSV4_FULL_PROMPT_LEN {PROMPT_LEN}u
#define DSV4_FULL_MAX_NEW {MAX_NEW}u
#define DSV4_FULL_GENERATED_LEN {len(generated)}u
"""
    sections = [
        emit_uint_array("dsv4_full_token", tokens),
        emit_float_array("dsv4_full_expected_base_logits", base_logits),
        emit_float_array("dsv4_full_expected_mtp_logits", mtp_logits),
        emit_uint_array("dsv4_full_expected_base_argmax", base_argmax),
        emit_uint_array("dsv4_full_expected_mtp_argmax", mtp_argmax),
        emit_uint_array("dsv4_full_expected_mtp_route_indices", mtp_routes),
        emit_float_array("dsv4_full_expected_mtp_route_weights", mtp_route_weights),
        emit_uint_array("dsv4_full_prompt", prompt_values),
        emit_uint_array("dsv4_full_expected_generated", generated),
    ]
    return preamble + "\n\n" + "\n\n".join(sections) + "\n\n#endif\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(build_header(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
