from __future__ import annotations

import argparse
from pathlib import Path

import torch

from .config import load_config
from .reference import MiniIndexer

ROOT = Path(__file__).resolve().parents[2]
CONFIG_PATH = ROOT / "tools" / "dsv4_mini" / "tiny_config.json"


def c_float(value: float) -> str:
    return float(torch.tensor(value, dtype=torch.float32).item()).hex() + "f"


def emit_array(
    name: str,
    values: torch.Tensor,
    ctype: str = "float",
    per_line: int = 4,
) -> str:
    flattened = values.detach().cpu().flatten().tolist()
    lines = [f"static const {ctype} {name}[{len(flattened)}] = {{"]
    for start in range(0, len(flattened), per_line):
        chunk = flattened[start : start + per_line]
        if ctype == "float":
            rendered = ", ".join(c_float(value) for value in chunk)
        else:
            rendered = ", ".join(f"{int(value)}u" for value in chunk)
        suffix = "," if start + per_line < len(flattened) else ""
        lines.append(f"    {rendered}{suffix}")
    lines.append("};\n")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    config = load_config(CONFIG_PATH)
    indexer = MiniIndexer(config, rate=4)
    heads = indexer.num_heads
    head_dim = indexer.head_dim
    top_k = indexer.top_k
    tokens = top_k + 3

    q = torch.linspace(-0.7, 0.9, heads * head_dim, dtype=torch.float32).view(
        heads, head_dim
    )
    source = torch.arange(tokens * head_dim, dtype=torch.float32).view(
        tokens, head_dim
    )
    compressed = (((source * 7 + 3) % 19) - 9) * 0.075
    head_weights = torch.tensor([0.8, -0.35, 1.15, 0.2], dtype=torch.float32)
    if head_weights.numel() != heads:
        raise RuntimeError("fixture expects four canonical index heads")

    dots = torch.einsum("hd,td->ht", q.float(), compressed.float())
    scores = torch.relu(dots) * (head_dim**-0.5)
    scores = (
        scores * (head_weights * (heads**-0.5)).unsqueeze(-1)
    ).sum(dim=0)

    top_scores, top_indices = torch.topk(scores, top_k, sorted=True)
    all_scores, all_indices = torch.topk(scores, tokens, sorted=True)
    if not torch.all(all_scores[:-1] - all_scores[1:] > 1e-6):
        raise RuntimeError("canonical fixture contains a top-k tie")

    content = "\n".join(
        [
            "/* Generated by tools/dsv4_mini/make_sparse_index_fixture.py.",
            " * Canonical formula: MiniIndexer.step post-projection scoring.",
            " * Do not edit by hand.",
            " */",
            "#ifndef DSV4_SPARSE_INDEX_VECTORS_H",
            "#define DSV4_SPARSE_INDEX_VECTORS_H",
            "",
            "#include <stddef.h>",
            "",
            f"#define DSV4_SI_HEADS {heads}u",
            f"#define DSV4_SI_TOKENS {tokens}u",
            f"#define DSV4_SI_HEAD_DIM {head_dim}u",
            f"#define DSV4_SI_TOPK {top_k}u",
            "",
            emit_array("dsv4_si_q", q),
            emit_array("dsv4_si_compressed", compressed),
            emit_array("dsv4_si_head_weights", head_weights),
            emit_array("dsv4_si_top_scores", top_scores),
            emit_array("dsv4_si_top_indices", top_indices, "size_t"),
            emit_array("dsv4_si_all_scores", all_scores),
            emit_array("dsv4_si_all_indices", all_indices, "size_t"),
            "#endif",
            "",
        ]
    )
    Path(args.output).write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
