from __future__ import annotations

import argparse
from pathlib import Path

import torch

from .config import load_config
from .reference import MiniAttention, MiniCompressor, _apply_partial_rope, _rope_cos_sin

ROOT = Path(__file__).resolve().parents[2]
CONFIG_PATH = ROOT / "tools" / "dsv4_mini" / "tiny_config.json"


def hf(value: float) -> str:
    return float(torch.tensor(value, dtype=torch.float32).item()).hex() + "f"


def array_text(name: str, values: torch.Tensor) -> str:
    flattened = torch.as_tensor(values, dtype=torch.float32).detach().flatten().tolist()
    output = [f"static const float {name}[{len(flattened)}] = {{"]
    for start in range(0, len(flattened), 4):
        chunk = flattened[start : start + 4]
        suffix = "," if start + 4 < len(flattened) else ""
        output.append("    " + ", ".join(hf(item) for item in chunk) + suffix)
    output.append("};\n")
    return "\n".join(output)


def make_compressor(config, overlap: bool):
    rate = 4
    output_dim = 4
    projection_dim = output_dim * (2 if overlap else 1)
    module = MiniCompressor(
        config,
        rate=rate,
        output_dim=output_dim,
        overlap=overlap,
        rope_dim=4,
    )
    with torch.no_grad():
        module.kv_proj.weight.zero_()
        module.gate_proj.weight.zero_()
        values = torch.arange(projection_dim * 4, dtype=torch.float32).view(
            projection_dim, 4
        )
        module.kv_proj.weight[:, :4].copy_(((values % 9) - 4) * 0.0375)
        module.gate_proj.weight[:, :4].copy_(
            (((values * 3 + 2) % 11) - 5) * 0.03125
        )
        module.position_bias.copy_(
            torch.linspace(-0.07, 0.09, rate * projection_dim).view(
                rate, projection_dim
            )
        )
        module.norm.weight.copy_(torch.tensor([0.85, 1.1, 0.95, 1.2]))

    base1 = torch.tensor(
        [
            [0.2, -0.4, 0.6, 0.1],
            [-0.3, 0.5, 0.2, -0.7],
            [0.9, -0.1, -0.2, 0.4],
            [0.15, 0.35, -0.55, 0.8],
        ]
    )
    base2 = torch.tensor(
        [
            [-0.6, 0.25, 0.45, -0.1],
            [0.7, -0.2, 0.05, 0.3],
            [-0.4, -0.5, 0.8, 0.2],
            [0.1, 0.9, -0.35, -0.45],
        ]
    )
    hidden1 = torch.zeros(1, rate, config.hidden_size)
    hidden2 = torch.zeros(1, rate, config.hidden_size)
    hidden1[0, :, :4] = base1
    hidden2[0, :, :4] = base2

    state = module.new_state(1, torch.device("cpu"), torch.float32)
    expected1 = module.push(hidden1, state)[:, -1].detach().clone()
    expected2 = module.push(hidden2, state)[:, -1].detach().clone()
    with torch.no_grad():
        kv1 = module.kv_proj(hidden1)[0]
        gate1 = module.gate_proj(hidden1)[0]
        kv2 = module.kv_proj(hidden2)[0]
        gate2 = module.gate_proj(hidden2)[0]
    return module, kv1, gate1, kv2, gate2, expected1[0], expected2[0]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True)
    args = parser.parse_args()
    config = load_config(CONFIG_PATH)

    rope_input = torch.linspace(-0.75, 0.9, config.head_dim).view(
        1, 1, 1, config.head_dim
    )
    position = torch.tensor([[7]], dtype=torch.long)
    cosine, sine = _rope_cos_sin(
        position,
        config.rope_head_dim,
        config.rope_theta,
        torch.float32,
    )
    rope_expected = _apply_partial_rope(
        rope_input, cosine, sine, config.rope_head_dim
    ).flatten()

    attention = MiniAttention(config, layer_idx=0).eval()
    with torch.no_grad():
        attention.sinks.copy_(torch.tensor([-0.2, 0.05, 0.3, -0.1]))
    q = torch.linspace(
        -0.6,
        0.8,
        config.num_attention_heads * config.head_dim,
    ).view(1, config.num_attention_heads, 1, config.head_dim)
    kv = torch.linspace(0.7, -0.5, 3 * config.head_dim).view(
        1, 1, 3, config.head_dim
    )
    attention_expected = attention._attention_with_sink(q, kv)[0, :, 0, :]

    csa = make_compressor(config, True)
    hca = make_compressor(config, False)
    parts = [
        "/* Generated by tools/dsv4_mini/make_attention_numeric_fixture.py.",
        " * Canonical source: tools/dsv4_mini/reference.py",
        " * Do not edit by hand.",
        " */",
        "#ifndef DSV4_ATTENTION_NUMERIC_VECTORS_H",
        "#define DSV4_ATTENTION_NUMERIC_VECTORS_H",
        "",
        array_text("dsv4_an_rope_input", rope_input),
        array_text("dsv4_an_rope_expected", rope_expected),
        array_text("dsv4_an_q", q),
        array_text("dsv4_an_kv", kv),
        array_text("dsv4_an_sinks", attention.sinks),
        array_text("dsv4_an_attention_expected", attention_expected),
    ]
    for prefix, data in (("csa", csa), ("hca", hca)):
        module, kv1, gate1, kv2, gate2, expected1, expected2 = data
        parts.extend(
            [
                array_text(f"dsv4_an_{prefix}_kv1", kv1),
                array_text(f"dsv4_an_{prefix}_gate1", gate1),
                array_text(f"dsv4_an_{prefix}_kv2", kv2),
                array_text(f"dsv4_an_{prefix}_gate2", gate2),
                array_text(f"dsv4_an_{prefix}_bias", module.position_bias),
                array_text(f"dsv4_an_{prefix}_norm_weight", module.norm.weight),
                array_text(f"dsv4_an_{prefix}_expected1", expected1),
                array_text(f"dsv4_an_{prefix}_expected2", expected2),
            ]
        )
    parts.extend(["#endif", ""])
    Path(args.output).write_text("\n".join(parts), encoding="utf-8")


if __name__ == "__main__":
    main()
