/* Generated by tools/dsv4_mini/make_moe_fixture.py.
 * Canonical source: tools/dsv4_mini/reference.py SparseMoE
 * Source commit: 1106f248ccea9bc3b06cb031e8ca58542e23c8c7
 * Do not edit by hand.
 */
#ifndef DSV4_MOE_VECTORS_H
#define DSV4_MOE_VECTORS_H

#define DSV4_MOE_HIDDEN 8u
#define DSV4_MOE_INTERMEDIATE 6u
#define DSV4_MOE_EXPERTS 8u
#define DSV4_MOE_TOPK 2u
#define DSV4_MOE_VOCAB 16u
#define DSV4_MOE_HASH_LAYERS 1u
#define DSV4_MOE_CASES 4u
#define DSV4_MOE_ROUTE_SCALE 0x1.8000000000000p+0f
#define DSV4_MOE_SWIGLU_LIMIT 0x1.4000000000000p+3f


static const unsigned dsv4_moe_case_layer[4] = {
    0u, 0u, 1u, 1u
};

static const unsigned dsv4_moe_case_id[4] = {
    0u, 1u, 2u, 3u
};

static const unsigned dsv4_moe_case_token[4] = {
    3u, 9u, 5u, 12u
};

static const float dsv4_moe_expected_output[32] = {
    0x1.0fa5320000000p-13f, 0x1.e2056e0000000p-14f, -0x1.33ece40000000p-14f, 0x1.d94ef00000000p-15f,
    0x1.7203800000000p-13f, 0x1.99eeb40000000p-15f, -0x1.e6dcdc0000000p-13f, 0x1.49ebc40000000p-13f,
    0x1.1d4fc80000000p-11f, -0x1.30b8dc0000000p-13f, -0x1.24ed2c0000000p-13f, -0x1.d2af800000000p-18f,
    -0x1.ecb7520000000p-13f, -0x1.96f1b60000000p-13f, -0x1.13013c0000000p-14f, 0x1.36a50c0000000p-12f,
    -0x1.ebc2c80000000p-12f, 0x1.5100a00000000p-13f, -0x1.e507dc0000000p-12f, -0x1.2eed400000000p-11f,
    0x1.9a82760000000p-14f, 0x1.3893fc0000000p-11f, -0x1.875f0a0000000p-13f, 0x1.764a000000000p-21f,
    0x1.4402540000000p-13f, -0x1.8267600000000p-14f, -0x1.3815c00000000p-13f, 0x1.1d20f40000000p-13f,
    -0x1.08d9c40000000p-13f, -0x1.9a0eac0000000p-14f, 0x1.3712820000000p-13f, -0x1.38518a0000000p-13f
};

static const unsigned dsv4_moe_expected_indices[8] = {
    6u, 7u, 4u, 5u, 1u, 6u, 1u, 6u
};

static const float dsv4_moe_expected_weights[8] = {
    0x1.7c53ba0000000p-1f, 0x1.83ac480000000p-1f, 0x1.7c2bd40000000p-1f, 0x1.83d42e0000000p-1f,
    0x1.7e7f680000000p-1f, 0x1.8180980000000p-1f, 0x1.79d2ae0000000p-1f, 0x1.862d540000000p-1f
};

#endif
