/* Generated by tools/dsv4_mini/make_sparse_index_fixture.py.
 * Canonical formula: MiniIndexer.step post-projection scoring.
 * Do not edit by hand.
 */
#ifndef DSV4_SPARSE_INDEX_VECTORS_H
#define DSV4_SPARSE_INDEX_VECTORS_H

#include <stddef.h>

#define DSV4_SI_HEADS 4u
#define DSV4_SI_TOKENS 7u
#define DSV4_SI_HEAD_DIM 8u
#define DSV4_SI_TOPK 4u

static const float dsv4_si_q[32] = {
    -0x1.6666660000000p-1f, -0x1.4bf9640000000p-1f, -0x1.318c640000000p-1f, -0x1.171f620000000p-1f,
    -0x1.f964c00000000p-2f, -0x1.c48abc0000000p-2f, -0x1.8fb0ba0000000p-2f, -0x1.5ad6b80000000p-2f,
    -0x1.25fcb40000000p-2f, -0x1.e245620000000p-3f, -0x1.78915c0000000p-3f, -0x1.0edd560000000p-3f,
    -0x1.4a52a00000000p-4f, -0x1.dbaa500000000p-6f, 0x1.71f5e00000000p-6f, 0x1.2fe5840000000p-4f,
    0x1.01a6d60000000p-3f, 0x1.6b5adc0000000p-3f, 0x1.d50ee20000000p-3f, 0x1.1f61740000000p-2f,
    0x1.543b780000000p-2f, 0x1.89157a0000000p-2f, 0x1.bdef7c0000000p-2f, 0x1.f2c9800000000p-2f,
    0x1.13d1c20000000p-1f, 0x1.2e3ec40000000p-1f, 0x1.48abc40000000p-1f, 0x1.6318c60000000p-1f,
    0x1.7d85c80000000p-1f, 0x1.97f2c80000000p-1f, 0x1.b25fca0000000p-1f, 0x1.cccccc0000000p-1f
};

static const float dsv4_si_compressed[56] = {
    -0x1.ccccce0000000p-2f, 0x1.3333340000000p-4f, 0x1.3333340000000p-1f, -0x1.3333340000000p-2f,
    0x1.ccccce0000000p-3f, -0x1.59999a0000000p-1f, -0x1.3333340000000p-3f, 0x1.8000000000000p-2f,
    -0x1.0cccce0000000p-1f, 0x0.0p+0f, 0x1.0cccce0000000p-1f, -0x1.8000000000000p-2f,
    0x1.3333340000000p-3f, 0x1.59999a0000000p-1f, -0x1.ccccce0000000p-3f, 0x1.3333340000000p-2f,
    -0x1.3333340000000p-1f, -0x1.3333340000000p-4f, 0x1.ccccce0000000p-2f, -0x1.ccccce0000000p-2f,
    0x1.3333340000000p-4f, 0x1.3333340000000p-1f, -0x1.3333340000000p-2f, 0x1.ccccce0000000p-3f,
    -0x1.59999a0000000p-1f, -0x1.3333340000000p-3f, 0x1.8000000000000p-2f, -0x1.0cccce0000000p-1f,
    0x0.0p+0f, 0x1.0cccce0000000p-1f, -0x1.8000000000000p-2f, 0x1.3333340000000p-3f,
    0x1.59999a0000000p-1f, -0x1.ccccce0000000p-3f, 0x1.3333340000000p-2f, -0x1.3333340000000p-1f,
    -0x1.3333340000000p-4f, 0x1.ccccce0000000p-2f, -0x1.ccccce0000000p-2f, 0x1.3333340000000p-4f,
    0x1.3333340000000p-1f, -0x1.3333340000000p-2f, 0x1.ccccce0000000p-3f, -0x1.59999a0000000p-1f,
    -0x1.3333340000000p-3f, 0x1.8000000000000p-2f, -0x1.0cccce0000000p-1f, 0x0.0p+0f,
    0x1.0cccce0000000p-1f, -0x1.8000000000000p-2f, 0x1.3333340000000p-3f, 0x1.59999a0000000p-1f,
    -0x1.ccccce0000000p-3f, 0x1.3333340000000p-2f, -0x1.3333340000000p-1f, -0x1.3333340000000p-4f
};

static const float dsv4_si_head_weights[4] = {
    0x1.99999a0000000p-1f, -0x1.6666660000000p-2f, 0x1.2666660000000p+0f, 0x1.99999a0000000p-3f
};

static const float dsv4_si_top_scores[4] = {
    0x1.33ee720000000p-4f, 0x1.d050880000000p-5f, 0x1.6d90ce0000000p-5f, 0x1.760b580000000p-6f
};

static const size_t dsv4_si_top_indices[4] = {
    1u, 3u, 2u, 0u
};

static const float dsv4_si_all_scores[7] = {
    0x1.33ee720000000p-4f, 0x1.d050880000000p-5f, 0x1.6d90ce0000000p-5f, 0x1.760b580000000p-6f,
    0x1.1968c40000000p-6f, 0x1.17ba420000000p-8f, 0x0.0p+0f
};

static const size_t dsv4_si_all_indices[7] = {
    1u, 3u, 2u, 0u,
    5u, 6u, 4u
};

#endif
