/* Generated by tools/dsv4_mini/make_attention_step_fixture.py.
 * Canonical sources: MiniAttention, GroupedLinear and RoPE helpers.
 * Do not edit by hand.
 */
#ifndef DSV4_ATTENTION_STEP_VECTORS_H
#define DSV4_ATTENTION_STEP_VECTORS_H

#include <stddef.h>

#define DSV4_STEP_HEADS 4u
#define DSV4_STEP_HEAD_DIM 4u
#define DSV4_STEP_ROPE_DIM 4u
#define DSV4_STEP_RAW_TOKENS 3u
#define DSV4_STEP_COMPRESSED_TOKENS 4u
#define DSV4_STEP_INDEX_HEADS 2u
#define DSV4_STEP_INDEX_DIM 4u
#define DSV4_STEP_INDEX_ROPE_DIM 4u
#define DSV4_STEP_TOPK 2u
#define DSV4_STEP_GROUPS 2u
#define DSV4_STEP_RANK 3u
#define DSV4_STEP_HIDDEN 6u
#define DSV4_STEP_POSITION 5

static const float dsv4_step_q[16] = {
    -0x1.3333340000000p-1f, -0x1.0369d00000000p-1f, -0x1.a740dc0000000p-2f, -0x1.47ae140000000p-2f,
    -0x1.d0369c0000000p-3f, -0x1.1111100000000p-3f, -0x1.47ae080000000p-5f, 0x1.b4e82c0000000p-5f,
    0x1.2c5f8c0000000p-3f, 0x1.eb851a0000000p-3f, 0x1.5555540000000p-2f, 0x1.b4e81a0000000p-2f,
    0x1.0a3d700000000p-1f, 0x1.3a06d40000000p-1f, 0x1.69d0360000000p-1f, 0x1.99999a0000000p-1f
};

static const float dsv4_step_raw[12] = {
    -0x1.ae147c0000000p-2f, -0x1.1eb8520000000p-4f, 0x1.1eb8520000000p-2f, -0x1.1eb8520000000p-1f,
    -0x1.ae147c0000000p-3f, 0x1.1eb8520000000p-3f, 0x1.f5c2900000000p-2f, -0x1.6666660000000p-2f,
    0x0.0p+0f, 0x1.6666660000000p-2f, -0x1.f5c2900000000p-2f, -0x1.1eb8520000000p-3f
};

static const float dsv4_step_compressed[16] = {
    -0x1.eb851e0000000p-2f, -0x1.eb851e0000000p-5f, 0x1.70a3d60000000p-2f, -0x1.70a3d60000000p-2f,
    0x1.eb851e0000000p-5f, 0x1.eb851e0000000p-2f, -0x1.eb851e0000000p-3f, 0x1.70a3d60000000p-3f,
    -0x1.147ae00000000p-1f, -0x1.eb851e0000000p-4f, 0x1.3333320000000p-2f, -0x1.ae147a0000000p-2f,
    0x0.0p+0f, 0x1.ae147a0000000p-2f, -0x1.3333320000000p-2f, 0x1.eb851e0000000p-4f
};

static const float dsv4_step_index_q[8] = {
    -0x1.0000000000000p-1f, -0x1.5075080000000p-2f, -0x1.41d41c0000000p-3f, 0x1.d41d600000000p-7f,
    0x1.7c57c20000000p-3f, 0x1.6db6da0000000p-2f, 0x1.0ea0ea0000000p-1f, 0x1.6666660000000p-1f
};

static const float dsv4_step_index_compressed[16] = {
    -0x1.47ae140000000p-3f, 0x1.47ae140000000p-4f, 0x1.47ae140000000p-2f, -0x1.eb851e0000000p-2f,
    -0x1.eb851e0000000p-3f, 0x0.0p+0f, 0x1.eb851e0000000p-3f, 0x1.eb851e0000000p-2f,
    -0x1.47ae140000000p-2f, -0x1.47ae140000000p-4f, 0x1.47ae140000000p-3f, 0x1.9999980000000p-2f,
    -0x1.9999980000000p-2f, -0x1.47ae140000000p-3f, 0x1.47ae140000000p-4f, 0x1.47ae140000000p-2f
};

static const float dsv4_step_index_head_weights[2] = {
    0x1.cccccc0000000p-1f, -0x1.99999a0000000p-2f
};

static const float dsv4_step_sinks[4] = {
    -0x1.99999a0000000p-3f, 0x1.99999a0000000p-5f, 0x1.3333340000000p-2f, -0x1.99999a0000000p-4f
};

static const float dsv4_step_oa[48] = {
    -0x1.99999a0000000p-3f, 0x1.3333340000000p-4f, -0x1.ccccce0000000p-3f, 0x1.99999a0000000p-5f,
    -0x1.0000000000000p-2f, 0x1.99999a0000000p-6f, -0x1.19999a0000000p-2f, 0x0.0p+0f,
    0x1.19999a0000000p-2f, -0x1.99999a0000000p-6f, 0x1.0000000000000p-2f, -0x1.99999a0000000p-5f,
    0x1.ccccce0000000p-3f, -0x1.3333340000000p-4f, 0x1.99999a0000000p-3f, -0x1.99999a0000000p-4f,
    0x1.6666660000000p-3f, -0x1.0000000000000p-3f, 0x1.3333340000000p-3f, -0x1.3333340000000p-3f,
    0x1.0000000000000p-3f, -0x1.6666660000000p-3f, 0x1.99999a0000000p-4f, -0x1.99999a0000000p-3f,
    0x1.3333340000000p-4f, -0x1.ccccce0000000p-3f, 0x1.99999a0000000p-5f, -0x1.0000000000000p-2f,
    0x1.99999a0000000p-6f, -0x1.19999a0000000p-2f, 0x0.0p+0f, 0x1.19999a0000000p-2f,
    -0x1.99999a0000000p-6f, 0x1.0000000000000p-2f, -0x1.99999a0000000p-5f, 0x1.ccccce0000000p-3f,
    -0x1.3333340000000p-4f, 0x1.99999a0000000p-3f, -0x1.99999a0000000p-4f, 0x1.6666660000000p-3f,
    -0x1.0000000000000p-3f, 0x1.3333340000000p-3f, -0x1.3333340000000p-3f, 0x1.0000000000000p-3f,
    -0x1.6666660000000p-3f, 0x1.99999a0000000p-4f, -0x1.99999a0000000p-3f, 0x1.3333340000000p-4f
};

static const float dsv4_step_ob[36] = {
    -0x1.ae147c0000000p-3f, 0x1.1eb8520000000p-5f, 0x1.1eb8520000000p-2f, -0x1.1eb8520000000p-4f,
    0x1.6666660000000p-3f, -0x1.6666660000000p-3f, 0x1.1eb8520000000p-4f, -0x1.1eb8520000000p-2f,
    -0x1.1eb8520000000p-5f, 0x1.ae147c0000000p-3f, -0x1.1eb8520000000p-3f, 0x1.ae147c0000000p-4f,
    -0x1.f5c2900000000p-3f, 0x0.0p+0f, 0x1.f5c2900000000p-3f, -0x1.ae147c0000000p-4f,
    0x1.1eb8520000000p-3f, -0x1.ae147c0000000p-3f, 0x1.1eb8520000000p-5f, 0x1.1eb8520000000p-2f,
    -0x1.1eb8520000000p-4f, 0x1.6666660000000p-3f, -0x1.6666660000000p-3f, 0x1.1eb8520000000p-4f,
    -0x1.1eb8520000000p-2f, -0x1.1eb8520000000p-5f, 0x1.ae147c0000000p-3f, -0x1.1eb8520000000p-3f,
    0x1.ae147c0000000p-4f, -0x1.f5c2900000000p-3f, 0x0.0p+0f, 0x1.f5c2900000000p-3f,
    -0x1.ae147c0000000p-4f, 0x1.1eb8520000000p-3f, -0x1.ae147c0000000p-3f, 0x1.1eb8520000000p-5f
};

static const size_t dsv4_step_selected[2] = {
    3u, 0u
};

static const float dsv4_step_selected_scores[2] = {
    0x1.2f1abe0000000p-6f, 0x1.f1e8240000000p-7f
};

static const float dsv4_step_expected_csa[6] = {
    -0x1.597bce0000000p-8f, 0x1.e3893c0000000p-6f, -0x1.e0fa240000000p-9f, 0x1.17361c0000000p-6f,
    -0x1.0efcd00000000p-9f, 0x1.3175cc0000000p-6f
};

static const float dsv4_step_expected_hca[6] = {
    -0x1.6d85440000000p-7f, 0x1.1787060000000p-5f, -0x1.49fcec0000000p-7f, 0x1.d203180000000p-7f,
    -0x1.2674980000000p-7f, 0x1.f58b740000000p-7f
};

static const float dsv4_step_expected_sliding[6] = {
    0x1.130ba40000000p-7f, 0x1.26fc520000000p-6f, 0x1.598dd40000000p-7f, 0x1.5f70180000000p-6f,
    0x1.a010040000000p-7f, 0x1.82b1320000000p-6f
};

#endif
